spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: h4kxqvwedh5t7q1z8yow
    password: pscale_pw_wM1vVLHio8vV71OU7Fh5vadh3GRLUL4vN4B6eZZIifr
    url: jdbc:mysql://eu-west.connect.psdb.cloud/bunker?sslMode=VERIFY_IDENTITY